default_settings: null
behaviors:
  default_ppo:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500
    max_steps: 50000
    time_horizon: 2048
    summary_freq: 1
    threaded: true
    self_play: null
    behavioral_cloning: null
  Hider:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500
    max_steps: 50000
    time_horizon: 2048
    summary_freq: 1
    threaded: true
    self_play:
      save_steps: 2000
      team_change: 1
      swap_steps: 5000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
  Seeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        gamma: 0.99
        strength: 0.05
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
        use_actions: false
        use_vail: false
        demo_path: demos/seeker_expert.demo
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500
    max_steps: 50000
    time_horizon: 2048
    summary_freq: 1
    threaded: true
    self_play:
      save_steps: 2000
      team_change: 1
      swap_steps: 5000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
  HideAndSeekAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500
    max_steps: 50000
    time_horizon: 2048
    summary_freq: 1
    threaded: true
    self_play:
      save_steps: 2000
      team_change: 1
      swap_steps: 5000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 1280
  height: 720
  quality_level: 1
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters:
  team_size:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3766
          value: 3
      name: initial
      completion_criteria:
        behavior: HideAndSeekAgent
        measure: reward
        min_lesson_length: 0
        signal_smoothing: true
        threshold: 0.7
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3767
          value: 3
      name: full_teams
      completion_criteria: null
  arena_size:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3768
          value: 20
      name: arena_size
      completion_criteria: null
  observation_radius:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3769
          value: 10
      name: observation_radius
      completion_criteria: null
checkpoint_settings:
  run_id: run33
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
